use std::{env, fs, path::PathBuf};

fn sanitize_name(name: &str) -> String {
    // make valid Rust ident: replace '-' with '_' and uppercase
    name.replace('-', "_").to_uppercase()
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let metadata = cargo_metadata::MetadataCommand::new().exec()?;

    let pkg_name = env::var("CARGO_PKG_NAME")?;
    let pkg_version = env::var("CARGO_PKG_VERSION")?;

    let my_pkg = metadata
        .packages
        .iter()
        .find(|p| p.name == pkg_name && p.version.to_string() == pkg_version)
        .ok_or("current package not found in metadata")?;

    let mut entries = Vec::new();
    for dep in &my_pkg.dependencies {
        if let Some(found) = metadata.packages.iter().find(|p| p.name == dep.name) {
            entries.push((dep.name.clone(), found.version.to_string()));
        } else {
            entries.push((dep.name.clone(), dep.req.to_string()));
        }
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let dest_path = out_dir.join("deps_versions.rs");

    let mut contents = String::new();
    contents.push_str("// Auto-generated by build.rs\n\n");

    for (name, ver) in entries {
        let ident = sanitize_name(&name);
        contents.push_str(&format!(
            "pub const DEP_{}_VERSION: &str = \"{}\";\n",
            ident, ver
        ));
    }

    fs::write(dest_path, contents)?;

    Ok(())
}
